apiVersion: batch/v1
kind: Job
metadata:
  name: form-teams
  namespace: contest
spec:
  template:
    spec:
      containers:
      - name: contest
        image: sakibalamin/contest:0.0.3
      restartPolicy: Never
